version: "3.9"
services:
  redis-data:
    container_name: "redis_data"
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    networks:
      - redis-network

networks:
  redis-network:
    name: redis-network
    driver: bridge
